### ISSUE TITLE
Joining Ruby ML list

### ISSUE THREAD

**Issue by arbox** [jedld/tensor_stream#2]
Dear @jedld 
I wonder if you want put your Tensor Stream project on our community resource list for ML in Ruby:
https://github.com/arbox/machine-learning-with-ruby

I've put already tensor_stream into Inbox, but you probably want to find another better place for it.

The list is visited daily by about 50 unique Rubyists, it's a good place to promote your work :)

**Comment by jedld** [comment]
Hi @arbox ,

Thanks! Yeah I think it would be great, though I'm holding off until it reaches version 1.0 as tensor_stream is still currently in heavy development. Also, I still need to get the guides and docs sorted out.

**Comment by jedld** [comment]
> Dear @jedld
> I wonder if you want put your Tensor Stream project on our community resource list for ML in Ruby:
> https://github.com/arbox/machine-learning-with-ruby
> 
> I've put already tensor_stream into Inbox, but you probably want to find another better place for it.
> 
> The list is visited daily by about 50 unique Rubyists, it's a good place to promote your work :)

Hi @arbox,

I've just release version 1.0.0, I'd love to have this project listed in your community resource list for ML

**Comment by arbox** [comment]
@jedld 
sure! 
I saw your post on RubyFlow, I'll add it as well!
Thank you a lot for your work on Ruby Ecosystem for Machine Learning!

**Comment by arbox** [comment]
@jedld Hey there!  I've just added your project to the ML list and mentioned it on Reddit and RubyFlow.

To connect your repository with other ML related Ruby projects feel free to add a `rubyml` topic/tag to this repo and include an Awesome Badge: https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-mentioned-badge
